### ISSUE TITLE
SDA can be driven high (violates i2c specification)

### ISSUE THREAD

**Issue by XMOS-JoeG** [xmos/lib_i2c#89] opened 2024-01-11 12:51 UTC
https://github.com/xmos/lib_i2c/blob/648351bed1e78190c057105221055064cd881122/lib_i2c/src/i2c_master.xc#L181

Both I2C bus lines should only ever be driven in open drain mode i.e. either drive low or drive high-z (input). This is the case for SCL but not the case for SDA when driving data on to the bus - it is driven high if the data is high. This is contrary to the specification and could lead to multiple hardware issues. (driving current into pullup supply voltage, multi voltage compatibility issues etc.)

Instead of:
p_sda <: data & 0x1;
Correct function here would be:
if (data & 1)
  p_sda :> void;
else
  p_sda <: 0;

I have made this change and done quick testing with success.

A similar change would be needed to the other i2c sources e.g. i2c_slave.xc and i2c_master_async.xc etc.

**Comment by ACascarino** [comment] 2024-01-11 14:19
Assigning @mbanth to bring to your attention - Joe proposes a simple fix for the 1b port implementation, where each line is a separate port. Will need regression testing but looks watertight on a quick inspection. The multibit port implementation is slightly trickier, since we can't make single pins on a port HiZ while others are outputting, but Joe suggests using the internal pullup mode of the port to at least mititate the issue - will probably need a note in documentation/in the release changelog that this behaviour has changed so that customers aren't surprised when the chip starts pulling up, as well as an option to toggle the old behaviour.

**Comment by mbanth** [comment] 2024-01-15 12:10
At a meeting on 15 January 2024, @andrewdewhurst, @mbanth, @xross, @timmace-xmos, and @tomblackie-xmos agreed to defer work on this item until the work occurs to incorporate fwk_io's I2C functionality with lib_i2c ([Jira AP-241](https://xmosjira.atlassian.net/browse/AP-241)).

**Comment by mfreeborn** [comment] 2024-09-25 12:29
Just stumbled across this issue after noticing this irregularity on my scope. Picture one clearly shows SDA being driven high, as documented in the first post. The top 2 traces are digital, the bottom 2 are analogue.

![before](https://github.com/user-attachments/assets/e9eee6ee-0065-4ff8-b656-e1eeca6609f7)

Updating the code results in a nice smooth rising edge from the action of the pull up resistor:

![after](https://github.com/user-attachments/assets/f05801e2-f1ce-43c1-8849-bcec0a46294c)

Would be nice to see this small change merged so that we don't have to maintain a different version of this library ourselves.

**Comment by jseaber** [comment] 2024-09-25 14:36
Confirmed. We've forked `lib_i2c` with this change, and it has tested well throughout the year.

**Comment by xross** [comment] 2024-10-31 11:17
Fixed in #98

**Closed** 2024-11-07 11:24 UTC
Labels: type:bug, size:S
